"""
export_best.py
--------------
Reads results/best_params.json and writes a submission-ready
vXX_round1_prosperity.py into imc-prosperity-4/ with the optimized params
baked in as class variables.

Usage:
    python export_best.py --version 50
    → writes ../imc-prosperity-4/v50_round1_prosperity.py
"""

import argparse
import json
import sys
from pathlib import Path

OPTIMIZER_DIR = Path(__file__).parent
ALGO_DIR      = OPTIMIZER_DIR.parent / "imc-prosperity-4"
RESULTS_DIR   = OPTIMIZER_DIR / "results"


def load_best() -> dict:
    path = RESULTS_DIR / "best_params.json"
    if not path.exists():
        print("No best_params.json found. Run optimizer.py first.")
        sys.exit(1)
    with open(path) as f:
        record = json.load(f)
    print(f"Loaded best params (score={record['score']:,.0f}, mode={record['mode']})")
    return record["params"]


def export(params: dict, version: int) -> Path:
    # Read the template
    template_path = OPTIMIZER_DIR / "trader_template.py"
    template_src  = template_path.read_text()

    # Build the class-variable block from params
    lines = [
        f'    """',
        f'    v{version} — optimizer-generated parameters.',
        f'    Score: (see results/best_params.json)',
        f'    """',
        f'',
        f'    POSITION_LIMIT = {{"ASH_COATED_OSMIUM": 80, "INTARIAN_PEPPER_ROOT": 80}}',
        f'    FAIR_VALUE     = {{"ASH_COATED_OSMIUM": 10_000}}',
        f'',
        f'    def __init__(self, params=None):',
        f'        # Baked-in optimized params (overridable via params arg)',
        f'        optimized = {json.dumps(params, indent=8)}',
        f'        self.p = {{**optimized, **(params or {{}})}}',
    ]

    # Write the new file: swap the class docstring + __init__ block
    # Strategy: replace the ParameterizedTrader header with a Trader class header
    out_src = template_src.replace(
        "class ParameterizedTrader:",
        "class Trader:",
    ).replace(
        'from trader_template import DEFAULT_PARAMS, PARAM_BOUNDS, ParameterizedTrader',
        '',
    )

    # Replace the __init__ with optimized values baked in
    old_init = (
        "    def __init__(self, params: dict = None):\n"
        "        self.p = {**DEFAULT_PARAMS, **(params or {})}"
    )
    new_init = (
        f"    def __init__(self, params: dict = None):\n"
        f"        _optimized = {json.dumps(params)}\n"
        f"        self.p = {{**_optimized, **(params or {{}})}}"
    )
    out_src = out_src.replace(old_init, new_init)

    # Strip the DEFAULT_PARAMS / PARAM_BOUNDS constants (not needed in submission)
    # (leave them — harmless, and keeps the file self-contained)

    # Add version docstring at top
    header = f'"""\nv{version}_round1_prosperity.py\nAuto-generated by optimizer/export_best.py\n"""\n\n'
    out_src = header + out_src

    out_path = ALGO_DIR / f"v{version}_round1_prosperity.py"
    out_path.write_text(out_src)
    print(f"Wrote → {out_path}")
    return out_path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", type=int, required=True,
                        help="Version number for the output file (e.g. 50)")
    args = parser.parse_args()

    params   = load_best()
    out_path = export(params, args.version)

    # Quick validation
    print("\nQuick validation on real 3-day data...")
    sys.path.insert(0, str(OPTIMIZER_DIR.parent / "imc-prosperity-4-backtester"))
    sys.path.insert(0, str(OPTIMIZER_DIR.parent / "imc-prosperity-4"))
    sys.path.insert(0, str(OPTIMIZER_DIR))

    from prosperity4bt.file_reader import PackageResourcesReader
    from prosperity4bt.models import TradeMatchingMode
    from prosperity4bt.runner import run_backtest
    from trader_template import ParameterizedTrader

    reader = PackageResourcesReader()
    days   = [(1, -2), (1, -1), (1, 0)]
    trader = ParameterizedTrader(params)
    total  = 0
    for rn, dn in days:
        res = run_backtest(trader, reader, rn, dn,
                           print_output=False,
                           trade_matching_mode=TradeMatchingMode.all,
                           no_names=True, show_progress_bar=False)
        last_ts = res.activity_logs[-1].timestamp
        day_pnl = sum(r.columns[-1] for r in reversed(res.activity_logs)
                      if r.timestamp == last_ts)
        print(f"  Day {dn:+d}: {day_pnl:,.0f}")
        total += day_pnl
    print(f"  Total: {total:,.0f}")


if __name__ == "__main__":
    main()
